#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"

sudo apt-get update
sudo apt-get -y install nginx
sudo echo "Hello World!" > |sudo tee/var/www/html/index.nginx-debian.html
service nginx start
