#!/usr/bin/env bash                                                                                                                           
#Configure your Nginx server to have a custom 404 page that contains the string                                                               
#shellcheck disable=SC2154                                                                                                                    
                                                                                                                                              
sudo apt-get update                                                                                                                           
sudo apt-get install -y nginx                                                                                                                 
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html                                                                          
new_string="listen 80 default_server;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/BvWnEiOoAEk permanent;"                            
sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-available/default                                                     
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html                                                                              
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"                                                                                                                                             
sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-available/default                                                     
sudo sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/nginx.conf                                                                                                                           
sudo service nginx restart
