#!/usr/bin/env bash
#Install and configure HAProxy

sudo apt update
sudo apt install haproxy -y
haproxy=/etc/default/haproxy
echo "ENABLED=1" | sudo tee -a $haproxy

path=/etc/haproxy/haproxy.cfg
config=\
"
frontend manage_entry
	  bind *:80
	  default_backend my_web_servers
backend my_web_servers
	balance static-rr
	server 16842-web-01 34.236.187.99:80 check
	server 16842-web-02 3.235.225.96:80 check
"

echo "$config" | sudo tee -a "$path"
sudo systemctl restart haproxy.service
