#!/usr/bin/env bash
# display:
#To infinity and beyond
#With a sleep 2 between each iteration
#I am invincible!!!
trap "echo I am invincible!!!" SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done